apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-streams-workload
spec:
  selector:
    matchLabels:
      app: kafka-streams-workload
  replicas: 1 # tells deployment to run n number of pods matching the template
  template:
    metadata:
      labels:
        app: kafka-streams-workload
    spec:
      containers:
      - name: kafka-streams-workload-generator
        image: ably77/airlineprediction-stream:latest
